---
# Add this section from starter kit
driver:
  name: ec2
  retryable_tries: 180

provisioner:
  name: chef_zero

transport:
  # ssh_key: ~/.ssh/path-to-pem.pem
  username: Administrator
  elevated: true

verifier:
  name: inspec

platforms:
  - name: windows-2016
    transport:
      name: winrm
    driver:
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            delete_on_termination: true

suites:
  - name: default
    run_list:
      - recipe[cps_cap::default]
    attributes:
